# .github/workflows/tar-portainer.yml
name: Auto .tar dockermanager directory

on:
  workflow_dispatch:  # manually triggered from the GitHub UI
  push:
    paths:
      - 'dockermanager/**'  # run only when portainer directory changes

jobs:
  tar-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create tar of portainer contents
        run: |
          tar -cvf dockermanager.tar -C dockermanager .

      - name: List files to confirm
        run: ls -lh
