name: Delete file from all history

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: "Path of the file to delete (e.g. dockermanager/app.js)"
        required: true

jobs:
  delete-file-history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-filter-repo
        run: |
          sudo apt-get update
          sudo apt-get install -y git-filter-repo

      - name: Delete file from all history
        run: |
          git filter-repo --force --invert-paths --path "${{ github.event.inputs.file_path }}"

      - name: Re-add GitHub remote using PAT
        run: |
          git remote add origin https://x-access-token:${{ secrets.PAT_FORCE_PUSH }}@github.com/${{ github.repository }}.git

      - name: Force push rewritten history (DANGEROUS!)
        run: |
          git push origin --force --all
          git push origin --force --tags
